### ISSUE TITLE
KeyError: "['organization_id'] not in index"

### ISSUE THREAD

**Issue by bobleegogogo** [koito19960406/ZenSVI#68]
Hi @koito19960406,

I try to use ZenSVI to download some Mapillary image but continuously get the following error:

It seems be a key error in the index?

--------------------
Loading cache files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 54/54 [00:00<00:00, 71.86it/s]
All tiles have already been processed.
Filtering data: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 42328/42328 [00:45<00:00, 926.40it/s]
Traceback (most recent call last):
  File "D:\00_2022_TUM\working\2024\2024_SVI\00_download_SVI.py", line 16, in <module>
    downloader.download_svi("./SVI_IAN", input_shp_file="./bbox/500samples.shp", buffer=100, **kwarg)
  File "C:\Users\haoli\Anaconda3\envs\SVI\lib\site-packages\zensvi\download\mly.py", line 530, in download_svi
    self._get_pids(
  File "C:\Users\haoli\Anaconda3\envs\SVI\lib\site-packages\zensvi\download\mly.py", line 243, in _get_pids
    pid = pid[
  File "C:\Users\haoli\Anaconda3\envs\SVI\lib\site-packages\pandas\core\frame.py", line 3813, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "C:\Users\haoli\Anaconda3\envs\SVI\lib\site-packages\pandas\core\indexes\base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "C:\Users\haoli\Anaconda3\envs\SVI\lib\site-packages\pandas\core\indexes\base.py", line 6133, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['organization_id'] not in index"
--------------------

**Comment by koito19960406** [comment]
Hi, thanks @bobleegogogo for the issue. 
I fixed this in #69, and you can update ZenSVI to v0.12.2. Please also refer to the updated example notebook.

**Comment by bobleegogogo** [comment]
Cool! Thanks @koito19960406
